### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by Aldmors** [victoriadrake/django-security-check#1]
Django Security Check identified issues:
Traceback (most recent call last):
File "/github/workspace/manage.py", line 5, in
from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by victoriadrake** [comment]
Hello Jakob. It would appear your project environment does not have a module named 'dotenv' installed.
